#!/bin/bash
PS3="==> "
echo " choose Backup option"
mkdir /backup
select option in Files Databases Exit
do
        case $option in
                Files)

          # What to backup.
          backup_files="/home /var/spool/mail /etc /root /boot /opt"

          # Where to backup to.
          dest="/backup"

          # Create archive filename.
          day=$(date +%A)
          hostname=$(hostname -s)
          archive_file="$hostname-$day.tgz"

          # Print start status message.
          echo "Backing up $backup_files to $dest/$archive_file"
          date
          echo

          # Backup the files using tar.
          tar czf $dest/$archive_file $backup_files

          # Print end status message.
          echo
          echo "Backup finished"
          date

          # Long listing of files in $dest to check file sizes.
          ls -lh $dest
                        ;;
                Databases)
			DATE=$(date +%d-%m-%Y-%H:%M)
			BACKUP_DIR="/backup/db-backup/"
			MYSQL="$(which mysql)"
			mysql -u root -p* -e 'show databases;'
			echo "1.Full Backup"
			echo "2.Manual Backup"
			read a
			if [ $a == 2 ]
			then

        			echo "Enter Database name for backup"
		        read DB
		        mysqldump -u root -p* $DB | gzip -9 > "$BACKUP_DIR/manual_backup/$DB-$DATE.sql.gz"
		        ls -al $BACKUP_DIR/manual_backup/
		        echo -e "\n"
		        echo -e "\e[1;34m *****Manual Backup Successful***** \e[0m"
		        echo -e "\n"

			else

		        databases=`$MYSQL -u root -p* -e "show databases"| grep -Ev "(database|Database|information_schema|performance_schema)"`
		        for db in $databases; do
                		mysqldump --force --opt -u root -p* --databases $db | gzip > "$BACKUP_DIR/full_backup/$db-$DATE.gz"
		        done
		        ls -al $BACKUP_DIR/full_backup/
		        echo -e "\n"
		        echo -e "\e[1;34m *****Full Backup Successful***** \e[0m"
		        echo -e "\n"

			fi
                        ;;
                Exit)
                        echo "Exit success"
			break
                        ;;
                *)
                        echo "plz choose valid option :)"
                        ;;
        esac
done
